devHudi/gatsby-starter-hoodie

- src/components/Article/Body/StyledMarkdown/index.jsx
This PR resolves #5 
- Issue : https://github.com/devHudi/gatsby-starter-hoodie/issues/5
> fix: resolve broken style caused by code located inside li tag

- src/components/Bio/index.jsx
This PR resolves #7 
- Issue : #7
> Resolve Kaggle issue

- src/components/Article/Body/StyledMarkdown/index.jsx
This PR resolves #10 
- Issue : #10
> Resolve scrollbar in the post

- src/assets/theme/index.js
- src/components/Article/Body/StyledMarkdown/index.jsx
- src/components/Article/Body/Toc/index.jsx
This PR resolves #12 
- Issue : #12
> feat: style code block scroll

- src/components/Title/index.jsx
This PR resolves #22 
- Issue : #22
> feat: add word-break into Title

- src/components/Article/Body/StyledMarkdown/index.jsx
- src/components/Article/Header/index.jsx
This PR resolves #24 
- Issue : #24
> feat: add word-break option into post

- gatsby-node.js
This PR resolves #26 
- Issue : #26
> feat: enhance slug system

- src/components/Article/Series/index.jsx
This PR resolves #29 
- Issue : #29
> feat: show count of posts in series

- src/components/Article/Series/index.jsx
This PR resolves #33 
- Issue : #33
> feat: add margin into post wrapper

- src/components/PostList/index.jsx
This PR resolves #32 
- Issue : #32
> feat: add word-break into Exceprt of PostList

- src/pages/tags.jsx
This PR resolves #31 
- Issue : #31
> feat: sort tags by count

- src/components/PostList/index.jsx
This PR resolves #14 
- Issue : #14
> fix: fix issue#14

- src/components/Bio/index.jsx
Adds email icon to bio
- Issue : `none`
> feat: add email in bio

- blog-config.js
`Bio` 컴포넌트에 이메일 아이콘 추가로 예시 블로그에도 이메일 아이콘 추가.
참고 : https://github.com/devHudi/gatsby-starter-hoodie/pull/44
- Issue : #47
> chore: add email link into Bio

- src/components/SideTagList/index.jsx
- src/pages/index.jsx
resolves #28, resolves #21
- Issue : #28, #21
> feat: implement SideTagList

- src/components/SideTagList/index.jsx
> feat: change text color

- src/components/SideTagList/index.jsx
> feat: add link to all

- src/components/SideTagList/index.jsx
> feat: change opacity to display

- src/components/PostList/index.jsx
> fix: fix infinite scrolling issue on mobile environment

- src/pages/tags.jsx
> feat: add margin top

- src/components/Layout/Header/index.jsx
- src/components/NoContent/index.jsx
- src/components/SeriesList/index.jsx
- src/pages/series.jsx
> feat: implement series page

- src/pages/series.jsx
> feat: make order of series reversed

- src/components/Article/Body/Toc/index.jsx
> feat: change styles of TOC

- gatsby-node.js
- src/components/Article/Series/index.jsx
- src/components/SeriesList/index.jsx
- src/pages/index.jsx
- src/templates/Series.jsx
resolves #62, resolves #65
- Issue : #62, #65
> feat: implement series detail page

- gatsby-node.js
> fix: fix routing issue

- src/templates/Series.jsx
> fix: resolve style issue

- src/components/SEO/index.jsx
- src/templates/Post.jsx
> fix: fix og description

- blog-config.js
add **kaggle** that existed in **blog-config.js**
- Issue : `none`
> add kaggle

- src/components/Article/Body/Toc/index.jsx
> feat: enhance style of TOC

- src/assets/theme/index.js
- src/components/Article/Body/StyledMarkdown/index.jsx
> feat: enhance style of blockquote

- src/assets/theme/index.js
- src/components/TextField/index.jsx
- src/pages/search.jsx
> feat: enhance style of search page

- src/components/Layout/Header/index.jsx
> fix: resolve icon rail position issue

- src/components/Article/Header/index.jsx
> feat: remove word-break style of article title

- src/components/Article/Body/StyledMarkdown/index.jsx
> feat: increase line height of ariticle

- src/assets/theme/index.js
- src/components/Article/Body/StyledMarkdown/index.jsx
> feat: enhance style of table row on dark mode

- src/components/Article/Body/StyledMarkdown/index.jsx
> feat: remove margin top of first element

- contents/posts/other-tips-kr/index.md
- contents/posts/other-tips/index.md
> docs: fix path of favicon

- src/components/Article/Body/Toc/index.jsx
> feat: change toc hiding threshold

- package.json
> chore: install minipass, sharp

- src/components/Article/Body/StyledMarkdown/index.jsx
fix broken style of inline code block
closes #131
> fix: fix broken inline code style

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/ci.yml
> Change main branch in github actions

- gatsby-browser.js
- src/components/Article/Body/PrismTheme/CommonStyle.jsx
- src/components/Article/Body/PrismTheme/DarkMode.jsx
- src/components/Article/Body/PrismTheme/LightMode.jsx
- src/components/Article/Body/PrismTheme/index.jsx
- src/components/Article/Body/StyledMarkdown/index.jsx
- src/components/Article/Body/index.jsx
> feat: code blocks respond to dark mode

- src/assets/theme/index.js
- src/components/Article/Body/StyledMarkdown/index.jsx
> feat: improve readability

- README.md
> docs: fix korean document link

- README-kr.md
- README.md
> docs: add star history

- README-kr.md
- README.md
> docs: change live demo url of readme

- src/components/Article/Body/StyledMarkdown/index.jsx
- src/components/PostList/index.jsx
- src/components/Title/index.jsx
> feat: improve typography style

- src/components/Article/Body/StyledMarkdown/index.jsx
> feat: hide anchor on mobile

- src/components/Article/Body/StyledMarkdown/index.jsx
> feat: change font size

- contents/posts/writing-guide-kr/index.md
- contents/posts/writing-guide/index.md
- gatsby-config.js
- package.json
- src/components/Article/Body/StyledMarkdown/index.jsx
- yarn.lock
> feat: add footnotes

- README-kr.md
- README.md
- blog-config.js
- contents/posts/about-hoodie-kr/index.md
- contents/posts/about-hoodie/index.md
- contents/posts/other-tips-kr/index.md
- contents/posts/other-tips/index.md
- contents/posts/quick-start-kr/index.md
- contents/posts/quick-start/index.md
- package.json
- src/components/Article/Footer/Comment.jsx
- src/components/Article/Footer/index.jsx
- yarn.lock
> feat: migrate from utterances to giscus

- blog-config.js
- contents/about/index.md
- gatsby-config.js
- gatsby-node.js
- src/components/Article/Body/index.jsx
- src/components/Article/Header/index.jsx
- src/components/Tab/index.jsx
- src/pages/about.jsx
- src/pages/index.jsx
- src/pages/search.jsx
- src/pages/series.jsx
- src/pages/tags.jsx
> feat: implement about page
